 CREATE TABLE GeneratedPlot (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId INTEGER NOT NULL,
	Start DATE NOT NULL,
	End DATE NOT NULL
);

CREATE TABLE MomentumLoad (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Amount INTEGER NOT NULL,
	Day DATE NOT NULL,
	Time TIME NOT NULL
);

CREATE INDEX idx_day ON MomentumLoad (Day);
CREATE INDEX idx_userId ON GeneratedPlot (UserId);
